"""initial migration

Revision ID: 271d80b2c5e
Revises: 436f8ca987a
Create Date: 2015-11-29 16:44:54.698515

"""

# revision identifiers, used by Alembic.
revision = '271d80b2c5e'
down_revision = '436f8ca987a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
